#!/bin/bash

sudo apt install jq
echo ""
read -p "Enter your account role arn: " user_role_arn

aws_credentials=$(aws sts assume-role --role-arn $user_role_arn  --role-session-name "RoleSession1")

export AWS_ACCESS_KEY_ID=$(echo $aws_credentials|jq '.Credentials.AccessKeyId'|tr -d '"')
export AWS_SECRET_ACCESS_KEY=$(echo $aws_credentials|jq '.Credentials.SecretAccessKey'|tr -d '"')
export AWS_SESSION_TOKEN=$(echo $aws_credentials|jq '.Credentials.SessionToken'|tr -d '"')

echo ""

echo "You can succesfuuly run 'terraform plan' command now "
