#!/bin/bash

sudo apt install jq


while true;
do
   echo ""	
   read -p "Enter your account role arn: " user_role_arn

   if [ -z $user_role_arn ]
   then
        echo ""   
	echo "You role arn is empty, try again!!!"
   else     
       	
        aws_credentials=$(aws sts assume-role --role-arn $user_role_arn  --role-session-name "RoleSession1" 2>/dev/null )
        if [[ -z $aws_credentials  ]]
        then
	   echo ""	
	   echo "incorrect arn,try again!!!"
	   continue
        else 	   
     
            export AWS_ACCESS_KEY_ID=$(echo $aws_credentials|jq '.Credentials.AccessKeyId'|tr -d '"')
     	    export AWS_SECRET_ACCESS_KEY=$(echo $aws_credentials|jq '.Credentials.SecretAccessKey'|tr -d '"')
     	    export AWS_SESSION_TOKEN=$(echo $aws_credentials|jq '.Credentials.SessionToken'|tr -d '"')

  	    echo ""

     	    echo "You can succesfuuly run 'terraform plan' command now "
	    echo ""
	    break
        fi	    
   fi
done
